package com.drunkncode.raw;

enum TokenType {
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

  BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, MOD,

  IDENTIFIER, STRING, NUMBER,

  AND, CLASS, ELSE, FALSE, FUN, OR, IF, NIL, WHILE, FOR, PRINT, PRINTLN, RETURN, SUPER, THIS, TRUE, VAR,

  QUESTION, COLON,

  BIT_OR, BIT_AND, BIT_XOR,

  BREAK, CONTINUE,

  EOF
}
